<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SenseVoiceInput.Core\SenseVoiceInput.Core.csproj" />
    <InternalsVisibleTo Include="SenseVoiceInput.Windows.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.28.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
